---
title: "1_RR_PrepareData"
author: "Nina-Alisa Kollakowski"
date: "`r Sys.Date()`"
output: html_document
---
## Spatial Contingency Data

```{r}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T1/Body Ownership_Behavioural/RScripts/allData.RData")
spatialContingencyData <- Result %>%
  group_by(id, view) %>%
  summarise(looking_s = sum(lookingDuration),
            legMovement_s = sum(legMovementDuration)) %>% #sum data by condition
  filter(view != "away") %>%
  tidyr::pivot_wider(names_from = view, values_from = c("looking_s", "legMovement_s")) %>%
  mutate(lookingScore = looking_s_mirrored/(looking_s_mirrored + looking_s_ego),
         legMovementScore = legMovement_s_mirrored/(legMovement_s_mirrored + legMovement_s_ego)) %>% #create contingency preference scores
  select(id, lookingScore, legMovementScore)
rm(Result)
```
## Temporal Contingency Data - Looking

```{r}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T1/fNIRS/AttentionCoding/lookingData.RData")
temporalContingencyData_looking <- looking_data %>%
  select(ID, condition, mean_looking) %>%
  tidyr::pivot_wider(names_from = condition, values_from = mean_looking) %>% #create contingency preference score
  mutate(lookingScore = delayed/(delayed + online)) %>%
  select(ID, lookingScore)
rm(looking_data)
```

## Temporal Contingency Data - fNIRS
```{r create time bins}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T1/fNIRS/RScripts/ROIData.RData")
n_bins <- 10
fnirsData_binned <- fnirsData_ROI_long %>%
  mutate(bins = ntile(time, n = n_bins)) %>%
  group_by(subject, condition, hemisphere, bins) %>%
  summarise(HbO = mean(HbO),
            HbR = mean(HbR))
fnirsData_binned$bins <- as.factor(fnirsData_binned$bins)
fnirsData_binned$condition <- droplevels(fnirsData_binned$condition)
```

```{r analyze left HbO}
#ANOVA
timeAnova_left_HbO <- ez::ezANOVA(fnirsData_binned[fnirsData_binned$hemisphere == "l",],
                          dv = HbO,
                          wid = subject,
                          within = c(bins, condition))
print(timeAnova_left_HbO)

#Post-Hoc T-Tests of time bins
bins_left_HbO <- data.frame(matrix(nrow = n_bins, ncol = 3))
colnames(bins_left_HbO) <- c("bins", "t", "p")
bins_left_HbO$bins <- 1:n_bins
for (i in levels(fnirsData_binned$bins)){
  currentTest <- fnirsData_binned %>%
    filter(bins == i,
           hemisphere == "l") %>%
    t.test(HbO ~ condition, data = ., paired = TRUE)
  bins_left_HbO[i, "p"] <- currentTest$p.value
  bins_left_HbO[i, "t"] <- currentTest$statistic
}

#compute difference score between conditions in significant time bins
left_HbO_diff <- fnirsData_binned %>%
  filter(hemisphere == "l",
         bins %in%  which(bins_left_HbO$p < 0.05)) %>%
  group_by(subject, condition) %>%
  summarise(m_HbO = mean(HbO)) %>%
  select(subject, condition, m_HbO) %>%
  tidyr::pivot_wider(names_from = condition, values_from = m_HbO) %>%
  mutate(leftHbOScore = delayed - online) %>%
  select(subject, leftHbOScore)
  
```

```{r analyze right HbO}
#ANOVA HbO right hemisphere
timeAnova_right_HbO <- ez::ezANOVA(fnirsData_binned[fnirsData_binned$hemisphere == "r",],
                           dv = HbO,
                           wid = subject,
                           within = c(bins, condition))
print(timeAnova_right_HbO)

bins_right_HbO <- data.frame(matrix(nrow = n_bins, ncol = 3))
colnames(bins_right_HbO) <- c("bins","t", "p")
bins_right_HbO$bins <- 1:n_bins
for (i in levels(fnirsData_binned$bins)){
  currentTest <- fnirsData_binned %>%
    filter(bins == i,
           hemisphere == "r") %>%
    t.test(HbO ~ condition, data = ., paired = TRUE)
  bins_right_HbO[i, "p"] <- currentTest$p.value
  bins_right_HbO[i, "t"] <- currentTest$statistic
}

#compute difference score between conditions in significant time bins
right_HbO_diff <- fnirsData_binned %>%
  filter(hemisphere == "r",
         bins %in%  which(bins_left_HbO$p < 0.05)) %>%
  group_by(subject, condition) %>%
  summarise(m_HbO = mean(HbO)) %>%
  select(subject, condition, m_HbO) %>%
  tidyr::pivot_wider(names_from = condition, values_from = m_HbO) %>%
  mutate(rightHbOScore = delayed - online) %>%
  select(subject, rightHbOScore)

```

```{r analyze left HbR}
timeAnova_left_HbR <- ez::ezANOVA(fnirsData_binned[fnirsData_binned$hemisphere == "l",],
                          dv = HbR,
                          wid = subject,
                          within = c(bins, condition))
print(timeAnova_left_HbR)
#no significant effects of condition
```

```{r analyze right HbR}

timeAnova_right_HbR <- ez::ezANOVA(fnirsData_binned[fnirsData_binned$hemisphere == "r",],
                           dv = HbR,
                           wid = subject,
                           within = c(bins, condition))
print(timeAnova_right_HbR)
#no significant effects of condition
```
```{r clean-up}
temporalContingencyData <- merge(temporalContingencyData_looking, 
                                 merge(left_HbO_diff, right_HbO_diff, by = "subject", all = TRUE),
                                 by.x = "ID", by.y = "subject", all = TRUE)
rm(list = c("n_bins", 
            "timeAnova_left_HbO", 
            "timeAnova_left_HbR", 
            "timeAnova_right_HbO",
            "timeAnova_right_HbR",
            "bins_left_HbO", 
            "bins_right_HbO",
            "temporalContingencyData_looking",
            "left_HbO_diff",
            "right_HbO_diff",
            "currentTest",
            "fnirsData_binned",
            "fnirsData_ROI_long"))
```

## Reaching to the Self Data

```{r}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T2/Reaching/RScripts/allData.RData")
reachingToSelfData <- Result %>%
  filter(!is.na(Contact_Success)) %>%
  group_by(ID, Target_Location_general) %>%
  summarise(n_trials = n(),
            proportionContact = sum(Contact_Success)/n_trials) %>%
  select(-n_trials) %>%
  tidyr::pivot_wider(names_from = Target_Location_general, values_from = proportionContact)
```

## Sensory Attenuation (EEG) Data
```{r}
sensoryAttenuationData <- read.csv("Z:/Längsschnitt Selbst/Auswertung/T2/EEG/Preprocessing_HAPPE/Trigger_SoundOnsetOhneAffe/ClusterBasedPermutationAnalysis_Fieldtrip/Significant_Clusters_ERP/meanClusterDifferences.csv")
```

## Mirror Self-Recognition Data
```{r}
library(dplyr)
mirrorSelfRecognitionData <- readxl::read_excel("Z:/Längsschnitt Selbst/Auswertung/T4/MirrorSelfRecognition/Hauptkodierung_LinaMöllen/Coding_MSR_T4_Lina_final.xlsx") %>%
  select(ID, Recognition)
```

## Video Self-Recognition Data
```{r}
library(dplyr)
library(readxl)

#load data from blind coding
videoSelfRecognitionData_blind <- read_excel("Z:/Längsschnitt Selbst/Auswertung/T4/VideoSelfRecognition/Coding_ExcelFiles/Hauptkodierung_AshleyChay/T4_SelfRecognition_Ashley_final.xlsx")

#load condition data
conditions <- read_excel("Z:/Längsschnitt Selbst/Auswertung/T4/VideoSelfRecognition/T4_SelfRecognition_Conditions.xlsx")

#merge together and only consider children that responded correctly in both conditions as recognizer
videoSelfRecognitionData <- merge(videoSelfRecognitionData_blind, conditions, by.x = c("ID", "Condition"), by.y = c("ID", "Video")) %>%
  select(ID, `self-recognition`, Condition.y) %>%
  tidyr::pivot_wider(names_from = Condition.y, values_from = `self-recognition`) %>%
  mutate(selfRecognition = ifelse(self == "y" & other == "n", 1, 0))

#clean-up
rm(conditions)
rm(videoSelfRecognitionData_blind)
```

## Body Size: Door Data
```{r}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T4/BodyAsObject/Door/RScripts/final_data_BodyAsObject_Door.RData")
bodySizeDoorData <- all_results %>%
  mutate(errors = ifelse(errors_binary == "Yes", 1, 0)) %>%
  select(ID, errors)

rm(all_results)
```

## Body Size: Toys Data
```{r}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T4/BodyAsObject/Toys/RScripts/allData.RData")
bodySizeToysData <- allData %>%
  mutate(error_binary = ifelse(errors == 0, 0, 1)) %>%
  select(id, toy, error_binary) %>%
  group_by(id) %>%
  summarise(m_errors = mean(error_binary))
rm(allData)
```

## Body as Obstacle data
```{r}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T4/BodyAsObject/Obstacle/RScripts/allData.RData")
bodyAsObstacle <- allData %>%
  mutate(error = ifelse(errors_binary == "Yes", 1, 0)) %>%
  group_by(ID) %>%
  summarise(m_errors = mean(error))
rm(allData)
```

## Self-Understanding Questionnaire data
```{r}
library(dplyr)
load("Z:/Längsschnitt Selbst/Auswertung/T4/Fragebögen/UCLA/UCLA.RData")
selfUnderstandingData <- cleandat %>%
  mutate(passed = (self_description_rel + self_recognition_rel + self_regulation_rel + autonomy_rel)/4) %>%
  select(ID, passed)
rm(cleandat)
```

## Placing Sticker on Self Data
```{r}
library(dplyr)
placingStickerData_buffer <- readxl::read_excel("Z:/Längsschnitt Selbst/Auswertung/T4/Placing/Coding_Placing_T4_StefanieKrammer.xlsx")
placingStickerData <- placingStickerData_buffer %>%
  mutate(correctPlace = ifelse(Placement == "of", 1, ifelse(Placement == -99, NA, 0))) %>%
  select(ID, Type, correctPlace) %>%
  na.omit() %>%
  group_by(ID) %>%
  summarise(m_correctTrials = mean(correctPlace))
rm(placingStickerData_buffer)
```

